name: Scheduled build

on:
  schedule:
  - cron:  '05 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger our build webhook on Netlify
      run: curl -X POST -d {} "${URL}${TOKEN}?trigger_title=${TITLE}"
      env:
        URL: "https://api.netlify.com/build_hooks/"
        TOKEN: ${{ secrets.NETLIFY_CRON_BUILD_HOOK }}
        TITLE: "triggered by GitHub cron action"
